language: node_js
cache: yarn
node_js:
  - stable

script: yarn test:unit

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: yarn test:unit --coverage --coverageReporters=text-lcov | coveralls
